### PR TITLE
Reimplemented particle sticking feature

### PR DESCRIPTION
**Pull request by irischang020**

### CODE REVIEW

**Comment by irischang020** [comment]
I noticed that in skopi/examples/notebooks/cspi_generate_synthetic_dataset_double-hit.ipynb cell [2], deeban used the following to model multi-hits.
```
# Soon obsolete way to assume multiple particles in the beam:
experiment.set_multi_particle_hit(True)
```

**Comment by chuckie82** [comment]
Let's just use FXS class.

There's a misnomer here. 
FXS experiments require random distribution of particles (i.e. not stuck together)
SPI experiments have particles stuck together (that we must veto before reconstruction).

So sticking feature is required in the SPIExperiment class

**Comment by irischang020** [comment]
Thanks for the clarification.
So I'll move the sticking feature to the SPI class instead of the FXS class.
And work on cleaning up the deprecated features.

**Comment by chuckie82** [comment]
could you look into the conflict with Ariana's new code?

**Comment by irischang020** [comment]
I added a function `add_fluence_jitter` in experiment/base.py to account for the fluence jitter from run to run as the focus size and particle positions change with photon energy and bandwidth. There is SASEBeam class in beam/sase.py  I implemented a while ago to model energy jitter in spikes. I noticed that @apeck12 also added a function `add_beam_jitter` in detector/base.py. Do we want to elaborate the difference a little bit?

**Comment by chuckie82** [comment]
add_beam_jitter would be the jitter in beam position shot-to-shot (perhaps needs a rename)

add_fluence_jitter should be shot-to-shot (if it's run to run, then needs modification)

**Comment by irischang020** [comment]
> add_fluence_jitter should be shot-to-shot (if it's run to run, then needs modification)
Yes the current implementation is for shot-to-shot.

**Comment by chuckie82** [comment]
@apeck12 could you review this PR and merge? add_fluence_jitter is another form of noise we can use for Exafel milestone

**Comment by apeck12** [comment]
Sounds good. I see a note about needing write access to be able to merge PRs, but I'm not sure how to check if I have that access level.

**Comment by irischang020** [comment]
@apeck12 I guess @chuckie82 meant to include `add_fluence_jitter` into the noise parameter, so the content would have dark noise, beam jitter, static noise and beam fluence jitter. `add_beam_jitter` seems to be related to beam pointing position relative to the detector, perhaps we could rename it to `add_beampointing_jitter`? Please feel free to make suggestions/changes!

**Comment by apeck12** [comment]
@irischang020, could you merge the changes in [PR#1](https://github.com/irischang020/skopi/pull/1) to your branch to append them to this commit? Here are the items that I revised or had questions about:

- `add_beam_jitter` was renamed to `offset_beam_center`.

- I revised particlePlacement.py. Here’s a visual check that the particles end up in the illuminated volume formed by the intersection of the (gas) jet and beam, and are properly aggregated or dispersed:

download-1

- In experiment/fxs.py, what is the purpose of the `gamma` parameter? The function `distribute_particles` only has the option of setting `sticking` to True or False rather than to a float. I’ve removed `gamma` and set `sticking=False` by default for the fxs class, but please discard the changes in fxs.py and ExampleFXS.py if `gamma` is required instead. In that case `distribute_particles` will have to be updated as well.

- In experiment/spi.py, why is fluence jitter a function of the particles’ positions, and is there a reference for the way you implemented `add_fluence_jitter`? Assuming that jitter is 1) an intrinsic property of the beam and 2) applicable to all experiment types, I’ve moved the relevant functions to beam/base.py and experiment/base.py and modeled fluence variation as being normally distributed.

- Unless reference and sample positions are supplied to the `HOLOExperiment` class, the positions of both particles are set to the origin. Assuming that the reference and sample particles will be randomly located in the illuminated volume, it seems like we could instead make use of the `distribute_particles` function with `sticking=False`. I also noticed that holo.py is the only `Experiment` class that continues to support the `set_orientation` and `set_position` functions. For consistency, I think it would make sense to either remove those functions or reintroduce them to the other `Experiment` classes. 

- Example scripts have been updated to accommodate recent changes, and all unit tests now terminate without errors.

**Comment by chuckie82** [comment]
@apeck12 let me know if you don't have merging privileges and waiting for me to merge this

**Comment by apeck12** [comment]
Sorry for the delay. I've made a few changes to the `add_fluence_jitter` function since Monday's discussion so I'll merge this as soon as those are committed.

**Comment by apeck12** [comment]
Summary of the recent changes:
- The `Experiment` class has been further updated to accommodate SASE beams after removing the `ReciprocalDetector` class. As before, the diffraction volume is constructed based on the highest anticipated wavevector to avoid out-of-bounds errors during slicing.
- The `set_positions` and `set_orientations` functions were reintroduced to the SPI class to make validation by comparison to the `detector.get_intensity_field(particle)` function possible. The parameter `jet_radius` is optional for this Experiment class; if set, the particle or its aggregate will be randomly positioned in the illuminated volume formed by the intersection of the jet and beam.
- The function `fluence_at_position` was added to the Beam class to enable modeling the fluence as a 2d Gaussian rather than uniform in the plane of the beam.
- Example scripts were updated to be consistent with the changes. All unit tests currently pass.

**Comment by irischang020** [comment]
[supplement]
Compute the diffraction pattern by setting a specific orientation in the Experiment class, or through the Detector class using the rotated particle should yield the same results if specifying the same return type and if we could sample every detector pixel given that the size of the mesh doesn't exceed the gpu capacity. Keeping `det.get_intensity_field(particle)` is for checking that the output of the Experiment and Detector classes are similar within an acceptable error due to the finite mesh sampling, though we typically generate diffraction patterns through Experiment class.

**Pull request merged**
